apiVersion: v1
kind: Service
metadata:
  name: app-rust
  labels:
    app: app-rust
spec:
  type: LoadBalancer
  selector:
    app: app-rust
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000