name: Rust app

on:
  push:
    branches:
      - "feature/**"
    paths:
      - app_rust/**

  pull_request:
    branches:
      - "feature/**"
    paths:
      - app_rust/**

defaults:
  run:
    working-directory: app_rust
    shell: bash

jobs:
  test_app:
    timeout-minutes: 2

    name: Test&lint app
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt

      - name: Run lint check (rustfmt)
        run: cd app; cargo fmt -- --check

      - name: Testing app
        run: cd app; cargo test

  build_push:
    needs: [test_app]
    timeout-minutes: 3

    name: Docker build and push image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sign in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - uses: docker/setup-buildx-action@v3
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: app_rust/
          file: app_rust/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops-lab-02-rust:latest

          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/devops-lab-02-rust:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/devops-lab-02-rust:buildcache,mode=max
